<?php

/**
 * Implements hook_menu().
 */
function islandora_batch_thesis_menu() {
  $items = array();

  $items['islandora/object/%islandora_object/manage/collection/thesis_batch'] = array(
    'title' => 'Thesis Batch',
    'access callback' => 'islandora_batch_thesis_menu_access',
    'access arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_thesis_batch_form', 2),
    'file' => 'includes/islandora_batch_thesis.form.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Menu access callback.
 */
function islandora_batch_thesis_menu_access($object) {
  if (!islandora_object_access(ISLANDORA_INGEST, $object)) {
    return FALSE;
  }
  $c = 'COLLECTION_POLICY';
  if (isset($object[$c]) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object[$c])) {
    $cp = new CollectionPolicy($object[$c]->content);

    return array_key_exists('ir:thesisCModel', $cp->getContentModels());
  }

  return FALSE;
}
